Django_Geonil_Web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.shortcuts import redirect
from django.conf.urls.static import static

def root(request):
    return redirect('blog:post_list')

urlpatterns = [
    # url(r'^$', root, name="root"),
    url(r'^$', lambda r: redirect('blog:post_list'), name="root"),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')), #blog.urls  / -> .으로
    url(r'^dojo/', include('dojo.urls', namespace='dojo')), #blog.urls  / -> .으로
    url(r'^accounts/', include('account.urls')), #blog.urls  / -> .으로
    url(r'^product/', include('product.urls', namespace='product')), #blog.urls  / -> .으로
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)




if settings.DEBUG:
    import debug_toolbar
    urlpatterns +=[
        url(r'^__debug__/',include(debug_toolbar.urls))
    ]

blog/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv
urlpatterns = [

    url(r'^$', views_cbv.post_list, name="post_list"),
    # url(r'^$', views.post_list, name="post_list"),
    url(r'^(?P<pk>\d+)/$', views_cbv.post_detail, name="post_detail"),

    url(r'^new/$', views.post_new, name="post_new"),
    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name="post_edit"),
    # url(r'^(?P<id>\d+)/edit/$', views.post_edit),

    url(r'^comments/$', views.comment_list, name="comment_list"),

    url(r'^cbv/new/$', views_cbv.post_new, name="post_new" ),
    url(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit, name="post_edit" ),
    url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete, name="post_delete" )
]

product/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name="product_list"),
    url(r'^(?P<pk>\d+)/$', views.product_detail, name="product_detail"),
    url(r'^new/$', views.product_new, name="product_new"),
    url(r'^(?P<id>\d+)/edit/$', views.product_edit, name="product_edit"),
    url(r'^(?P<pk>\d+)/delete/$', views.product_delete, name="product_delete"),


]

Django_Geonil_Web/templates/layout.html
{% load static %}<!-- 이렇게 쓰는 것을 추천합니다. 로드를 해줘야 사용이 가능합니다. -->

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name='viewport' content='width=device-width' />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.1/yeti/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="/static/style.css"> -->
    <link rel="stylesheet" href="{% static "style.css" %}"> <!-- 이렇게 쓰는 것을 추천합니다. -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>

    <title>{%block title%}{%endblock%}</title>
    <script type="text/javascript">
    {% if user.is_authenticated %}
        window.onload = function(){
          location1 = location.href
          if(location1.match("login")){
        

          }
        }
    {% endif %}
    </script>
  </head>
  <body class="page-legacybootstrap?theme=0">
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
      <div class="container">
          <a class="navbar-brand" href="#">Geonil</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="main-nav">
          <ul class="nav navbar-nav ml-lg-5">
            <li class="nav-item"><a class="nav-link" href="{% url "root"%}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="">About</a></li>
            <li class="nav-item"><a class="nav-link" href="">Content</a></li>
            <li class="nav-item"><a class="nav-link" href="{%url "product:product_list"%}">Product</a></li>
          </ul>
          <ul class="nav navbar-nav ml-auto">
            {% if not user.is_authenticated %}
              <li id="log" class="nav-item"><a class="nav-link" href="{% url "signup"%}">회원가입</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url "login" %}?next={{request.path}}">로그인</a></li>
            {% else %}
              <li id="out" class="nav-item"><a class="nav-link" href="{% url "profile" %}">프로필</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url "logout" %}?next={{request.path}}">로그아웃</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <br><br><br><br><br>
{% if messages %}
<div class="container">
  {% for message in messages%}
  <div class="alert alert-{{ message.tags }}">
    [{{message.tags}}] {# 메세지 레벨#}
    {{message.message}} {# 실제메세지 내용#}
  </div>
  {% endfor%}
</div>
{% endif%}



  {% block content %}
  {% endblock%}


  <div class="" id="page-footer">
    <div class="container">
      <p class="text-muted">
        &copy; 2018. Geonil Jang
      </p>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.bundle.min.js"></script>
  </body>
</html>