Django_Geonil_Web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.shortcuts import redirect
from django.conf.urls.static import static

def root(request):
    return redirect('blog:post_list')

urlpatterns = [
    # url(r'^$', root, name="root"),
    url(r'^$', lambda r: redirect('blog:post_list'), name="root"),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')), #blog.urls  / -> .으로
    url(r'^dojo/', include('dojo.urls', namespace='dojo')), #blog.urls  / -> .으로
    url(r'^accounts/', include('account.urls')), #blog.urls  / -> .으로
    url(r'^product/', include('product.urls', namespace='product')), #blog.urls  / -> .으로
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)




if settings.DEBUG:
    import debug_toolbar
    urlpatterns +=[
        url(r'^__debug__/',include(debug_toolbar.urls))
    ]

blog/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv
urlpatterns = [

    url(r'^$', views_cbv.post_list, name="post_list"),
    # url(r'^$', views.post_list, name="post_list"),
    url(r'^(?P<pk>\d+)/$', views_cbv.post_detail, name="post_detail"),

    url(r'^new/$', views.post_new, name="post_new"),
    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name="post_edit"),
    # url(r'^(?P<id>\d+)/edit/$', views.post_edit),

    url(r'^comments/$', views.comment_list, name="comment_list"),

    url(r'^cbv/new/$', views_cbv.post_new, name="post_new" ),
    url(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit, name="post_edit" ),
    url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete, name="post_delete" )
]

blog/models.py
import re
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.forms import ValidationError
from imagekit.models import ImageSpecField
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.





#경도위도 검증 함수 구현하여 아래 모델에 적용하기
def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$',value):
        raise ValidationError('Invalid Lnglat Type')



class Post(models.Model):
    STATUS_CHOICES1 = ( #2018-06-28
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdraw'),
    )
    STATUS_CHOICES2 = ( #2018-06-28
        ('g', 'Good'),
        ('b', 'Bad'),
        ('s', 'Sad'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    #author = models.CharField(max_length=20, verbose_name="작성자")
    title = models.CharField(max_length=100,
                             # choices=(
                             #     ('제목1','제목1 레이블'), #선택 박스를 넣어 줄 수 있다
                             #     ('제목2','제목2 레이블'),
                             #     ('제목3','제목3 레이블'),
                             #     )
                             verbose_name="제목", help_text='포스팅 제목을 입력해주세요. 최대 100자 내외.') #길이제한
    content = models.TextField(verbose_name="내용" ) #길이제한 없음
    # photo = models.ImageField(blank=True, upload_to='blog/post/%Y/%m/%d')
    #방법2 원본을 날리고 썸으로 만들기
    photo = ProcessedImageField(blank=True, upload_to='blog/post/%Y/%m/%d',
                                         processors=[Thumbnail(300,300)],
                                         format = 'JPEG',
                                         options= {'quality':60}
                                     )
#방법 1 원본이 있고 원본을 통한 썸네일 처리
    # photo_thubnail = ImageSpecField(source="photo",
    #                                     processors=[Thumbnail(300,300)],
    #                                     format = 'JPEG',
    #                                     options= {'quality':60}
    #                                 )

    tags = models.CharField(max_length=100, blank=True)
    lnglat = models.CharField(max_length=50, validators = [lnglat_validator] ,help_text="경도/위도 포맷으로 입력." ,blank=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES1, default='d') #2018-06-28
    tag_set = models.ManyToManyField('Tag', blank=True)
    feeling = models.CharField(max_length=1, choices=STATUS_CHOICES2, default='g', verbose_name="기분")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
      ordering = ['-id'] #id로 내림 차순 정렬을 기본으로 정렬하겠다. [안에 여러 조건을 줄 수는 있지만 1가지 조건을사용하는 것을 추천]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args = [self.id] )


class Comment(models.Model):
    post = models.ForeignKey(Post) # post 모델에 대한 외래키로 쓰겠다.
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Post
from Django_Geonil_Web.widgets.naver_map_point_widget import NaverMapPointWidget



class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = '__all__'
        widgets = {
            'lnglat':NaverMapPointWidget(attrs={'width':600,'height':300}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from django.db.models import Q
from django.http import Http404
from django.conf import settings
from .forms import PostForm
from django.contrib import messages

def post_list(request):

    qs = Post.objects.all().prefetch_related('tag_set', 'comment_set')
    q = request.GET.get('q','')  #-> 해당 함수 호출 될 때 파라미터 q에 해당 하는 값이 있다면 값을 가져와라
    if q:
        qs = qs.filter( Q(title__icontains=q) | Q(content__icontains=q) )
                            # form 테그를 이용하여 파라미터를 던져서 해당 주소로 갈때 실행 되는 함수가
                             #이 함수 이기 때문에 render와 동일한 장소에 쿼리 처리 를 보여주고 있구만.
    return render(request, 'blog/post_list.html',{
        'post_list':qs,
    })

#view.py에 쿼리셋을 정의하고 데이터를 데이터 베이스로 부터 가져오기 실습



def post_detail(request, id):

    post = get_object_or_404(Post, id=id) # 아래 4줄과 동일한 1줄이다
    # try:
    #     post = Post.objects.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404
    return render(request, 'blog/post_detail.html',{
        'post':post,
    })



def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            messages.info(request, "새 글이 등록되었습니다.")
            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html',{
        "form":form,
    })

def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            messages.success(request, "포스팅을 수정했습니다.")
            return redirect(post)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html',{
        "form":form,
    })


def comment_list(request):
    # comment_list = Comment.objects.all()
    comment_list = Comment.objects.all().select_related('post')
    return render(request, 'blog/comment_list.html', {
        'comment_list' : comment_list,
    })

blog/templates/blog/comment_list.html
{% extends 'blog/layout.html'%}

{%block content%}
<ul>
{% for comment in comment_list %}
<li>{{comment}} {{comment.post}}</li>
{% endfor%}
</ul>
{%endblock%}

blog/templates/blog/post_confirm_delete.html
<h1>{{post}}삭제확인</h1>

정말 삭제하시겠습니까?
<form class="" action="" method="post">
  {% csrf_token%}
  <a href="{{post.get_absolute_url}}">아니요. 취소</a>
  <input type="submit" name="" value="예. 삭제하겠습니다.">
</form>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
<!-- 3번째방법구현 -->
{%load imagekit%}

{% block title %}
  {{post.title}}
{% endblock %}

{% block content %}
<!-- 여기는 작성글  -->
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h2>{{post.title}}</h2>
      <!-- <img src="/media/{{ post.photo }}" alt="as" style="max-width:100%;"> -->
      {% if post.photo %}
      <!-- <img src="{{ post.photo_thubnail.url }}" alt="as" style="max-width:100%;"> -->
      <img src="{{ post.photo.url }}" alt="" style="max-width:100%;">

      {% thumbnail "100x100" post.photo %}
      <img src="{{ post.photo.url }}" alt="as" style="max-width:50%;max-height:50%;">

      {% thumbnail "100x100" post.photo as thum%}
      <img src="{{thum.url}}" width="{{thum.width}}" height="thum.height" alt="">

      {% thumbnail "100x100" post.photo -- style="" onclick="alert('Hello')" class="" %}

<!-- 3번째방법구현 -->
      {% thumbnail "100x100" post.photo%}
      {% endif %}
      <p>{{post.content|linebreaks}}</p>
      <small>by {{post.user}}</small>
      <small>at {{post.updated_at}}</small>

      <hr>
      <!-- 여기는 댓글. -->
      <h3>Comment</h3>
      {%for comment in post.comment_set.all%}
      <ol>
      <li>
        {{comment.message}}
        작성자 : {{comment.author}}
        <small>작성시간 : {{comment.update_at}}</small>
        <small>해당글 : {{comment.post}}</small>
      </li>
      </ol>
      {%endfor%}
      <hr>
      <a href="{% url "blog:post_list" %}" class="btn btn-primary">글 목록</a>
      <a href="{% url "blog:post_edit" post.id %}" class="btn btn-default">수정하기</a>
    </div>
  </div>
</div>


{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container" style="margin-top:100px;">
<div class="row">
  <div class="col-sm-12">
    <form class="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table class="table table-hover">
        {{ form.as_table}}
      </table>
      <input type="submit" value="저장" class="btn btn-primary">
    </form>
  </div>
</div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block title %}
  {{post.title}}
{% endblock %}

{% block content %}


<div class="container">
  <div class="jumbotron text-center" style="background-image: url(http://cdn.greatdeals.com.sg/wp-content/uploads/2018/03/14165126/line-friends-needle-brown-628x362.jpg); background-size: 100%;">
    <h1>Geonil's Blog <sub>By geonil</sub></h1>
    <p>여러분의 친구 건일</p>
    <p>
      <a href="http://localhost:3007" class="btn btn-lg btn-primary">안뇽&raquo;</a>
    </p>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="alert alert-info">
          많은 글을 등록해주세요.
      </div>

      <div class="">
        <form action="" method="get">
          <input type="text" name="q" value="" >
          <input type="submit" name="" value="검색" class="btn btn-primary">
        </form>
        <a href="{% url "blog:post_new" %}" class="pull-left" style="float:right">글 작성</a>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>수정일</th>
          </tr>
        </thead>
        <tbody>
          {% for post in post_list %}
            <tr>
              <td>{{post.id}}</td>
              <td><a href="{% url "blog:post_detail" post.id %}">{{post.title}}</a>
                {% for tag in post.tag_set.all %}
                <span class="label label-info">{{ tag.name }}</span>
                {% endfor %}
              </td>
              <!-- <a href="/blog/detail/{{post.id}}">{{post.title}}</a> -->
              <td><small>by {{post.user}}</small></td>
              <td><small>at {{post.updated_at}}</small></td>
              <td>

              </td>
            </tr>
          {% endfor%}
        </tbody>
      </table>
    </div>
  </div>
</div>






{% endblock %}