Django_Geonil_Web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.shortcuts import redirect
from django.conf.urls.static import static

def root(request):
    return redirect('blog:post_list')

urlpatterns = [
    # url(r'^$', root, name="root"),
    url(r'^$', lambda r: redirect('blog:post_list'), name="root"),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')), #blog.urls  / -> .으로
    url(r'^dojo/', include('dojo.urls', namespace='dojo')), #blog.urls  / -> .으로
    url(r'^accounts/', include('account.urls')), #blog.urls  / -> .으로
    url(r'^product/', include('product.urls', namespace='product')), #blog.urls  / -> .으로
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)




if settings.DEBUG:
    import debug_toolbar
    urlpatterns +=[
        url(r'^__debug__/',include(debug_toolbar.urls))
    ]

blog/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv
urlpatterns = [

    url(r'^$', views_cbv.post_list, name="post_list"),
    # url(r'^$', views.post_list, name="post_list"),
    url(r'^(?P<pk>\d+)/$', views_cbv.post_detail, name="post_detail"),

    url(r'^new/$', views.post_new, name="post_new"),
    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name="post_edit"),
    # url(r'^(?P<id>\d+)/edit/$', views.post_edit),

    url(r'^comments/$', views.comment_list, name="comment_list"),

    url(r'^cbv/new/$', views_cbv.post_new, name="post_new" ),
    url(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit, name="post_edit" ),
    url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete, name="post_delete" )
]

product/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name="product_list"),
    url(r'^(?P<pk>\d+)/$', views.product_detail, name="product_detail"),
    url(r'^new/$', views.product_new, name="product_new"),
    url(r'^(?P<id>\d+)/edit/$', views.product_edit, name="product_edit"),
    url(r'^(?P<pk>\d+)/delete/$', views.product_delete, name="product_delete"),


]

product/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.forms import ValidationError
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
# Create your models here.

def len_validator(value):
    if(len(value) > 80):
        raise ValidationError('최대 글자 수는 100자를 초과 할 수 없습니다.')

class Product(models.Model):
    user= models.CharField(max_length=20, verbose_name="작성자", help_text="작성자를 입력해 주세요.")
    title = models.CharField(max_length=100, verbose_name="제목", help_text="포스팅 제목을 입력해주세요. 최대 100자 내외.", validators=[len_validator])
    content = models.TextField(verbose_name="내용")
    photo = models.ImageField(blank=True, upload_to='product/post/%Y/%m/%d')
    #방법 1 원본이 있고 원본을 통한 썸네일 처리
    photo_thubnail = ImageSpecField(source="photo",
                                        processors=[Thumbnail(300,300)],
                                        format = 'JPEG',
                                        options= {'quality':60}
                                    )
    user_agent = models.CharField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
      ordering = ['-id'] #id로 내림 차순 정렬을 기본으로 정렬하겠다. [안에 여러 조건을 줄 수는 있지만 1가지 조건을사용하는 것을 추천]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product:product_detail', args=[self.id])

class After(models.Model):
    product = models.ForeignKey(Product)
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

product/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            #커스텀 가능
            'user_agent':forms.HiddenInput,
        }

product/views.py
from django.shortcuts import render , get_object_or_404, redirect
from .models import Product
from .forms import ProductForm
from django.contrib import messages
from django.views.generic import ListView, DetailView,DeleteView
from django.core.urlresolvers import reverse_lazy
# Create your views here.



from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


product_delete = DeleteView.as_view(model=Product, success_url=reverse_lazy('product:product_list'))

def index(request):
    user_list = User.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(user_list, 10)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    return render(request, 'pro/user_list.html', { 'users': users })




def product_list(request):

    element = Product.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(element, 5)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    return render(request, 'product/product_list.html',{
        "elements":element,
        'users': users
    })








# product_detail = DetailView.as_view(model=Product)
def product_detail(request, pk):
    element = get_object_or_404(Product, id=pk)
    return render(request, 'product/product_detail.html',{
        "element":element
    })

def product_new(request):
    if request.method =="POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, "새 글이 등록되었습니다.")
            return redirect(product)
    else:
        form = ProductForm()
    return render(request, 'product/product_new.html',{
        "form":form,
    })


def product_edit(request, id):
    element = get_object_or_404(Product, id=id)
    if request.method =="POST":
        form = ProductForm(request.POST, request.FILES, instance=element)
        if form.is_valid():
            product = form.save()
            messages.success(request, "포스팅을 수정했습니다.")
            return redirect(product)
    else:
        form = ProductForm(instance=element)
    return render(request, 'product/product_new.html',{
        "form":form,
    })

product/templates/product/product_confirm_delete.html
<h1>{{product.title}}삭제확인</h1>
정말 삭제하시겠습니까?
<form class="" action="" method="post">
  {% csrf_token%}
  <a href="{{product.get_absolute_url}}">아니요. 취소</a>
  <input type="submit" name="" value="예. 삭제하겠습니다.">
</form>

product/templates/product/product_detail.html
{% extends "product/layout.html" %}
<!-- 3번째방법구현 -->
{%load imagekit%}

{%block content%}
<div class="container" style="margin-top:100px;">
  <div class="row">
    <div class="col-sm-12">
      <h1>작성글 확인</h1>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>번호</th><th>제목</th><th>내용</th><th> </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            {% if element.photo %}

            {% thumbnail "100x100" element.photo%}
            <img src="{{ element.photo_thubnail.url }}" alt="as" style="max-width:50%;max-height:50%;">

            {% thumbnail "100x100" element.photo as thum%}
            <img src="{{thum.url}}" width="{{thum.width}}" height="thum.height" alt="">

            {% thumbnail "100x100" element.photo -- style="" onclick="alert('Hello')" class="" %}

            {% endif %}
          </tr>
          <tr>
            <td>{{element.id}}</td><td>{{element.title}}</td><td>{{element.content|linebreaks}}</td><td><a href="{% url "product:product_edit" element.pk %}" class="btn btn-primary">수정하기</a> <a href="{% url "product:product_delete" element.pk %}" class="btn btn-danger">삭제하기</a></td>
          </tr>
          <tr>
          </tr>
        </tbody>
      </table>
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <h3>댓글</h3>
            <table class="table table-hover">
              {% for comment in element.after_set.all %}
              <tr>
                <td>작성자 : {{comment.author}}</td>
                <td>{{comment.message}}</td>
                <td><small>작성시간 : {{comment.update_at}}</small></td>
                <td><small>해당글 : {{comment.product}}</small></td>
              </tr>
              {% endfor%}
            </table>
            </ol>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 pull-right">
            <a href="{%url "product:product_list"%}" class="btn btn-primary">리스트</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock%}

product/templates/product/product_list.html
{% extends "product/layout.html" %}



    {%block content%}
    <div class="container" style="margin-top:100px;height:500px">
      <div class="row">
        <div class="col-sm-12">
          <h1>리스트 확인</h1>

          <table class="table table-hover">
            <thead>
              <tr>
                <th>번호</th><th>작성자</th><th>제목</th><th>작성일</th><th>수정일</th>
              </tr>
            </thead>
            <tbody>
              {% for ele in users%}
              <tr>
                <td>{{ele.id}}</td>
                <td>{{ele.user}}</td>
                <td>
                  <a href="{%url "product:product_detail" ele.id %}">{{ele.title|linebreaks}}</a>
                </td><td>{{ele.created_at}}</td><th>{{ele.update_at}}</th>
              </tr>
              {% endfor%}
            </tbody>
          </table>
          <a href="{% url "product:product_new" %}" class="btn btn-primary">새 글쓰기</a>
        </div>
      </div>
    </div>
<br><br>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation example" style="padding-left:40%;">
{% if users.has_other_pages %}
              <ul class="pagination" >
                <li class="page-item">
{% if users.has_previous %}
                    <a class="page-link" href="?page={{ users.previous_page_number }}">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="sr-only">Previous</span>
                    </a>
{% else %}
                    <a class="page-link" href="#" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="sr-only">Previous</span>
                    </a>
{% endif %}
                 </li>
{% for i in users.paginator.page_range %}
{% if users.number == i %}
                  <li class="page-item"><a class="page-link" style="color:red">{{ i }}</a></li>
{% else %}
                  <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
{% endif %}
{% endfor %}
{% if users.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{ users.next_page_number }}">&raquo;</a></li>
{% else %}
                  <li class="disabled"><a a class="page-link">&raquo;</a></li>
{% endif %}
              </ul>
{% endif %}

            </nav>
        </div>
      </div>
    </div>


    {%endblock%}

product/templates/product/product_new.html
{% extends "product/layout.html" %}



    {%block content%}
    <div class="container" style="margin-top:100px;">
    <div class="row">
      <div class="col-sm-12">
        <form class="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <table class="table table-hover">
            {{ form.as_table}}
          </table>
          <input type="submit" value="저장" class="btn btn-primary"> <a href="{%url "product:product_list"%}"><input type="button"value="돌아가기" class="btn btn-primary"></a>
        </form>
      </div>
    </div>
    </div>

    <script type="text/javascript">
      let dom = document.getElementById('{{ form.user_agent.id_for_label}}');
      dom.value = navigator.userAgent
    </script>
    {%endblock%}